// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p15
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_MOTORTYPESUPPORTC_3TXG9Y_H_
#define _TAO_IDL_MOTORTYPESUPPORTC_3TXG9Y_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "MotorC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace Actuators
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< Actuators::Motor, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> MotorSeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_ACTUATORS_MOTORTYPESUPPORT__VAR_OUT_CH_)
#define _ACTUATORS_MOTORTYPESUPPORT__VAR_OUT_CH_

  class MotorTypeSupport;
  typedef MotorTypeSupport *MotorTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        MotorTypeSupport
      >
    MotorTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        MotorTypeSupport
      >
    MotorTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  MotorTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef MotorTypeSupport_ptr _ptr_type;
    typedef MotorTypeSupport_var _var_type;
    typedef MotorTypeSupport_out _out_type;

    // The static operations.
    static MotorTypeSupport_ptr _duplicate (MotorTypeSupport_ptr obj);

    static void _tao_release (MotorTypeSupport_ptr obj);

    static MotorTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static MotorTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MotorTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MotorTypeSupport (void);

    

    virtual ~MotorTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    MotorTypeSupport (const MotorTypeSupport &);

    void operator= (const MotorTypeSupport &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_ACTUATORS_MOTORDATAWRITER__VAR_OUT_CH_)
#define _ACTUATORS_MOTORDATAWRITER__VAR_OUT_CH_

  class MotorDataWriter;
  typedef MotorDataWriter *MotorDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        MotorDataWriter
      >
    MotorDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        MotorDataWriter
      >
    MotorDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  MotorDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef MotorDataWriter_ptr _ptr_type;
    typedef MotorDataWriter_var _var_type;
    typedef MotorDataWriter_out _out_type;

    // The static operations.
    static MotorDataWriter_ptr _duplicate (MotorDataWriter_ptr obj);

    static void _tao_release (MotorDataWriter_ptr obj);

    static MotorDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static MotorDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MotorDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::Actuators::Motor & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::Actuators::Motor & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::Actuators::Motor & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::Actuators::Motor & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::Actuators::Motor & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::Actuators::Motor & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::Actuators::Motor & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::Actuators::Motor & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Actuators::Motor & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Actuators::Motor & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MotorDataWriter (void);

    

    virtual ~MotorDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    MotorDataWriter (const MotorDataWriter &);

    void operator= (const MotorDataWriter &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_ACTUATORS_MOTORDATAREADER__VAR_OUT_CH_)
#define _ACTUATORS_MOTORDATAREADER__VAR_OUT_CH_

  class MotorDataReader;
  typedef MotorDataReader *MotorDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        MotorDataReader
      >
    MotorDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        MotorDataReader
      >
    MotorDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  MotorDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef MotorDataReader_ptr _ptr_type;
    typedef MotorDataReader_var _var_type;
    typedef MotorDataReader_out _out_type;

    // The static operations.
    static MotorDataReader_ptr _duplicate (MotorDataReader_ptr obj);

    static void _tao_release (MotorDataReader_ptr obj);

    static MotorDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static MotorDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MotorDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::Actuators::MotorSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::Actuators::MotorSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::Actuators::MotorSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::Actuators::MotorSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::Actuators::Motor & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::Actuators::Motor & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::Actuators::MotorSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::Actuators::MotorSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::Actuators::MotorSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::Actuators::MotorSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::Actuators::MotorSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::Actuators::MotorSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::Actuators::MotorSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::Actuators::MotorSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::Actuators::MotorSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Actuators::Motor & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Actuators::Motor & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MotorDataReader (void);

    

    virtual ~MotorDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    MotorDataReader (const MotorDataReader &);

    void operator= (const MotorDataReader &);
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module Actuators

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace Actuators
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< Actuators::Steering, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> SteeringSeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_ACTUATORS_STEERINGTYPESUPPORT__VAR_OUT_CH_)
#define _ACTUATORS_STEERINGTYPESUPPORT__VAR_OUT_CH_

  class SteeringTypeSupport;
  typedef SteeringTypeSupport *SteeringTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        SteeringTypeSupport
      >
    SteeringTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        SteeringTypeSupport
      >
    SteeringTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  SteeringTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef SteeringTypeSupport_ptr _ptr_type;
    typedef SteeringTypeSupport_var _var_type;
    typedef SteeringTypeSupport_out _out_type;

    // The static operations.
    static SteeringTypeSupport_ptr _duplicate (SteeringTypeSupport_ptr obj);

    static void _tao_release (SteeringTypeSupport_ptr obj);

    static SteeringTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static SteeringTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static SteeringTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    SteeringTypeSupport (void);

    

    virtual ~SteeringTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    SteeringTypeSupport (const SteeringTypeSupport &);

    void operator= (const SteeringTypeSupport &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_ACTUATORS_STEERINGDATAWRITER__VAR_OUT_CH_)
#define _ACTUATORS_STEERINGDATAWRITER__VAR_OUT_CH_

  class SteeringDataWriter;
  typedef SteeringDataWriter *SteeringDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        SteeringDataWriter
      >
    SteeringDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        SteeringDataWriter
      >
    SteeringDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  SteeringDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef SteeringDataWriter_ptr _ptr_type;
    typedef SteeringDataWriter_var _var_type;
    typedef SteeringDataWriter_out _out_type;

    // The static operations.
    static SteeringDataWriter_ptr _duplicate (SteeringDataWriter_ptr obj);

    static void _tao_release (SteeringDataWriter_ptr obj);

    static SteeringDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static SteeringDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static SteeringDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::Actuators::Steering & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::Actuators::Steering & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::Actuators::Steering & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::Actuators::Steering & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::Actuators::Steering & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::Actuators::Steering & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::Actuators::Steering & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::Actuators::Steering & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Actuators::Steering & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Actuators::Steering & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    SteeringDataWriter (void);

    

    virtual ~SteeringDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    SteeringDataWriter (const SteeringDataWriter &);

    void operator= (const SteeringDataWriter &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_ACTUATORS_STEERINGDATAREADER__VAR_OUT_CH_)
#define _ACTUATORS_STEERINGDATAREADER__VAR_OUT_CH_

  class SteeringDataReader;
  typedef SteeringDataReader *SteeringDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        SteeringDataReader
      >
    SteeringDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        SteeringDataReader
      >
    SteeringDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  SteeringDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef SteeringDataReader_ptr _ptr_type;
    typedef SteeringDataReader_var _var_type;
    typedef SteeringDataReader_out _out_type;

    // The static operations.
    static SteeringDataReader_ptr _duplicate (SteeringDataReader_ptr obj);

    static void _tao_release (SteeringDataReader_ptr obj);

    static SteeringDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static SteeringDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static SteeringDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::Actuators::SteeringSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::Actuators::SteeringSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::Actuators::SteeringSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::Actuators::SteeringSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::Actuators::Steering & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::Actuators::Steering & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::Actuators::SteeringSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::Actuators::SteeringSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::Actuators::SteeringSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::Actuators::SteeringSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::Actuators::SteeringSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::Actuators::SteeringSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::Actuators::SteeringSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::Actuators::SteeringSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::Actuators::SteeringSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Actuators::Steering & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Actuators::Steering & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    SteeringDataReader (void);

    

    virtual ~SteeringDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    SteeringDataReader (const SteeringDataReader &);

    void operator= (const SteeringDataReader &);
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module Actuators

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_ACTUATORS_MOTORTYPESUPPORT__TRAITS_)
#define _ACTUATORS_MOTORTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::Actuators::MotorTypeSupport>
  {
    static ::Actuators::MotorTypeSupport_ptr duplicate (
        ::Actuators::MotorTypeSupport_ptr p);
    static void release (
        ::Actuators::MotorTypeSupport_ptr p);
    static ::Actuators::MotorTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Actuators::MotorTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_ACTUATORS_MOTORDATAWRITER__TRAITS_)
#define _ACTUATORS_MOTORDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::Actuators::MotorDataWriter>
  {
    static ::Actuators::MotorDataWriter_ptr duplicate (
        ::Actuators::MotorDataWriter_ptr p);
    static void release (
        ::Actuators::MotorDataWriter_ptr p);
    static ::Actuators::MotorDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Actuators::MotorDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_ACTUATORS_MOTORDATAREADER__TRAITS_)
#define _ACTUATORS_MOTORDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::Actuators::MotorDataReader>
  {
    static ::Actuators::MotorDataReader_ptr duplicate (
        ::Actuators::MotorDataReader_ptr p);
    static void release (
        ::Actuators::MotorDataReader_ptr p);
    static ::Actuators::MotorDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Actuators::MotorDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_ACTUATORS_STEERINGTYPESUPPORT__TRAITS_)
#define _ACTUATORS_STEERINGTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::Actuators::SteeringTypeSupport>
  {
    static ::Actuators::SteeringTypeSupport_ptr duplicate (
        ::Actuators::SteeringTypeSupport_ptr p);
    static void release (
        ::Actuators::SteeringTypeSupport_ptr p);
    static ::Actuators::SteeringTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Actuators::SteeringTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_ACTUATORS_STEERINGDATAWRITER__TRAITS_)
#define _ACTUATORS_STEERINGDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::Actuators::SteeringDataWriter>
  {
    static ::Actuators::SteeringDataWriter_ptr duplicate (
        ::Actuators::SteeringDataWriter_ptr p);
    static void release (
        ::Actuators::SteeringDataWriter_ptr p);
    static ::Actuators::SteeringDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Actuators::SteeringDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_ACTUATORS_STEERINGDATAREADER__TRAITS_)
#define _ACTUATORS_STEERINGDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::Actuators::SteeringDataReader>
  {
    static ::Actuators::SteeringDataReader_ptr duplicate (
        ::Actuators::SteeringDataReader_ptr p);
    static void release (
        ::Actuators::SteeringDataReader_ptr p);
    static ::Actuators::SteeringDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Actuators::SteeringDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "MotorTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

