// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p15
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376


#include "MotorTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "MotorTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for Actuators::MotorTypeSupport.

Actuators::MotorTypeSupport_ptr
TAO::Objref_Traits<Actuators::MotorTypeSupport>::duplicate (
    Actuators::MotorTypeSupport_ptr p)
{
  return Actuators::MotorTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Actuators::MotorTypeSupport>::release (
    Actuators::MotorTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Actuators::MotorTypeSupport_ptr
TAO::Objref_Traits<Actuators::MotorTypeSupport>::nil (void)
{
  return Actuators::MotorTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Actuators::MotorTypeSupport>::marshal (
    const Actuators::MotorTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Actuators::MotorTypeSupport::MotorTypeSupport (void)
{}

Actuators::MotorTypeSupport::~MotorTypeSupport (void)
{
}

Actuators::MotorTypeSupport_ptr
Actuators::MotorTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MotorTypeSupport::_duplicate (
      dynamic_cast<MotorTypeSupport_ptr> (_tao_objref)
    );
}

Actuators::MotorTypeSupport_ptr
Actuators::MotorTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MotorTypeSupport::_duplicate (
      dynamic_cast<MotorTypeSupport_ptr> (_tao_objref)
    );
}

Actuators::MotorTypeSupport_ptr
Actuators::MotorTypeSupport::_nil (void)
{
  return 0;
}

Actuators::MotorTypeSupport_ptr
Actuators::MotorTypeSupport::_duplicate (MotorTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Actuators::MotorTypeSupport::_tao_release (MotorTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Actuators::MotorTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Actuators/MotorTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Actuators::MotorTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Actuators/MotorTypeSupport:1.0";
}

::CORBA::Boolean
Actuators::MotorTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for Actuators::MotorDataWriter.

Actuators::MotorDataWriter_ptr
TAO::Objref_Traits<Actuators::MotorDataWriter>::duplicate (
    Actuators::MotorDataWriter_ptr p)
{
  return Actuators::MotorDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Actuators::MotorDataWriter>::release (
    Actuators::MotorDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Actuators::MotorDataWriter_ptr
TAO::Objref_Traits<Actuators::MotorDataWriter>::nil (void)
{
  return Actuators::MotorDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Actuators::MotorDataWriter>::marshal (
    const Actuators::MotorDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Actuators::MotorDataWriter::MotorDataWriter (void)
{}

Actuators::MotorDataWriter::~MotorDataWriter (void)
{
}

Actuators::MotorDataWriter_ptr
Actuators::MotorDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MotorDataWriter::_duplicate (
      dynamic_cast<MotorDataWriter_ptr> (_tao_objref)
    );
}

Actuators::MotorDataWriter_ptr
Actuators::MotorDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MotorDataWriter::_duplicate (
      dynamic_cast<MotorDataWriter_ptr> (_tao_objref)
    );
}

Actuators::MotorDataWriter_ptr
Actuators::MotorDataWriter::_nil (void)
{
  return 0;
}

Actuators::MotorDataWriter_ptr
Actuators::MotorDataWriter::_duplicate (MotorDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Actuators::MotorDataWriter::_tao_release (MotorDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Actuators::MotorDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Actuators/MotorDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Actuators::MotorDataWriter::_interface_repository_id (void) const
{
  return "IDL:Actuators/MotorDataWriter:1.0";
}

::CORBA::Boolean
Actuators::MotorDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for Actuators::MotorDataReader.

Actuators::MotorDataReader_ptr
TAO::Objref_Traits<Actuators::MotorDataReader>::duplicate (
    Actuators::MotorDataReader_ptr p)
{
  return Actuators::MotorDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Actuators::MotorDataReader>::release (
    Actuators::MotorDataReader_ptr p)
{
  ::CORBA::release (p);
}

Actuators::MotorDataReader_ptr
TAO::Objref_Traits<Actuators::MotorDataReader>::nil (void)
{
  return Actuators::MotorDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Actuators::MotorDataReader>::marshal (
    const Actuators::MotorDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Actuators::MotorDataReader::MotorDataReader (void)
{}

Actuators::MotorDataReader::~MotorDataReader (void)
{
}

Actuators::MotorDataReader_ptr
Actuators::MotorDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MotorDataReader::_duplicate (
      dynamic_cast<MotorDataReader_ptr> (_tao_objref)
    );
}

Actuators::MotorDataReader_ptr
Actuators::MotorDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MotorDataReader::_duplicate (
      dynamic_cast<MotorDataReader_ptr> (_tao_objref)
    );
}

Actuators::MotorDataReader_ptr
Actuators::MotorDataReader::_nil (void)
{
  return 0;
}

Actuators::MotorDataReader_ptr
Actuators::MotorDataReader::_duplicate (MotorDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Actuators::MotorDataReader::_tao_release (MotorDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Actuators::MotorDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Actuators/MotorDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Actuators::MotorDataReader::_interface_repository_id (void) const
{
  return "IDL:Actuators/MotorDataReader:1.0";
}

::CORBA::Boolean
Actuators::MotorDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for Actuators::SteeringTypeSupport.

Actuators::SteeringTypeSupport_ptr
TAO::Objref_Traits<Actuators::SteeringTypeSupport>::duplicate (
    Actuators::SteeringTypeSupport_ptr p)
{
  return Actuators::SteeringTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Actuators::SteeringTypeSupport>::release (
    Actuators::SteeringTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Actuators::SteeringTypeSupport_ptr
TAO::Objref_Traits<Actuators::SteeringTypeSupport>::nil (void)
{
  return Actuators::SteeringTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Actuators::SteeringTypeSupport>::marshal (
    const Actuators::SteeringTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Actuators::SteeringTypeSupport::SteeringTypeSupport (void)
{}

Actuators::SteeringTypeSupport::~SteeringTypeSupport (void)
{
}

Actuators::SteeringTypeSupport_ptr
Actuators::SteeringTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SteeringTypeSupport::_duplicate (
      dynamic_cast<SteeringTypeSupport_ptr> (_tao_objref)
    );
}

Actuators::SteeringTypeSupport_ptr
Actuators::SteeringTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SteeringTypeSupport::_duplicate (
      dynamic_cast<SteeringTypeSupport_ptr> (_tao_objref)
    );
}

Actuators::SteeringTypeSupport_ptr
Actuators::SteeringTypeSupport::_nil (void)
{
  return 0;
}

Actuators::SteeringTypeSupport_ptr
Actuators::SteeringTypeSupport::_duplicate (SteeringTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Actuators::SteeringTypeSupport::_tao_release (SteeringTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Actuators::SteeringTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Actuators/SteeringTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Actuators::SteeringTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Actuators/SteeringTypeSupport:1.0";
}

::CORBA::Boolean
Actuators::SteeringTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for Actuators::SteeringDataWriter.

Actuators::SteeringDataWriter_ptr
TAO::Objref_Traits<Actuators::SteeringDataWriter>::duplicate (
    Actuators::SteeringDataWriter_ptr p)
{
  return Actuators::SteeringDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Actuators::SteeringDataWriter>::release (
    Actuators::SteeringDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Actuators::SteeringDataWriter_ptr
TAO::Objref_Traits<Actuators::SteeringDataWriter>::nil (void)
{
  return Actuators::SteeringDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Actuators::SteeringDataWriter>::marshal (
    const Actuators::SteeringDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Actuators::SteeringDataWriter::SteeringDataWriter (void)
{}

Actuators::SteeringDataWriter::~SteeringDataWriter (void)
{
}

Actuators::SteeringDataWriter_ptr
Actuators::SteeringDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SteeringDataWriter::_duplicate (
      dynamic_cast<SteeringDataWriter_ptr> (_tao_objref)
    );
}

Actuators::SteeringDataWriter_ptr
Actuators::SteeringDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SteeringDataWriter::_duplicate (
      dynamic_cast<SteeringDataWriter_ptr> (_tao_objref)
    );
}

Actuators::SteeringDataWriter_ptr
Actuators::SteeringDataWriter::_nil (void)
{
  return 0;
}

Actuators::SteeringDataWriter_ptr
Actuators::SteeringDataWriter::_duplicate (SteeringDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Actuators::SteeringDataWriter::_tao_release (SteeringDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Actuators::SteeringDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Actuators/SteeringDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Actuators::SteeringDataWriter::_interface_repository_id (void) const
{
  return "IDL:Actuators/SteeringDataWriter:1.0";
}

::CORBA::Boolean
Actuators::SteeringDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for Actuators::SteeringDataReader.

Actuators::SteeringDataReader_ptr
TAO::Objref_Traits<Actuators::SteeringDataReader>::duplicate (
    Actuators::SteeringDataReader_ptr p)
{
  return Actuators::SteeringDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Actuators::SteeringDataReader>::release (
    Actuators::SteeringDataReader_ptr p)
{
  ::CORBA::release (p);
}

Actuators::SteeringDataReader_ptr
TAO::Objref_Traits<Actuators::SteeringDataReader>::nil (void)
{
  return Actuators::SteeringDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Actuators::SteeringDataReader>::marshal (
    const Actuators::SteeringDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Actuators::SteeringDataReader::SteeringDataReader (void)
{}

Actuators::SteeringDataReader::~SteeringDataReader (void)
{
}

Actuators::SteeringDataReader_ptr
Actuators::SteeringDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SteeringDataReader::_duplicate (
      dynamic_cast<SteeringDataReader_ptr> (_tao_objref)
    );
}

Actuators::SteeringDataReader_ptr
Actuators::SteeringDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SteeringDataReader::_duplicate (
      dynamic_cast<SteeringDataReader_ptr> (_tao_objref)
    );
}

Actuators::SteeringDataReader_ptr
Actuators::SteeringDataReader::_nil (void)
{
  return 0;
}

Actuators::SteeringDataReader_ptr
Actuators::SteeringDataReader::_duplicate (SteeringDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Actuators::SteeringDataReader::_tao_release (SteeringDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Actuators::SteeringDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Actuators/SteeringDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Actuators::SteeringDataReader::_interface_repository_id (void) const
{
  return "IDL:Actuators/SteeringDataReader:1.0";
}

::CORBA::Boolean
Actuators::SteeringDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

