// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p15
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_MOTORC_YKXMMT_H_
#define _TAO_IDL_MOTORC_YKXMMT_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace Actuators
{

  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:47

  enum MotorDirection
  {
    MOTOR_FORWARD,
    MOTOR_BACKWARD,
    MOTOR_END
  };

  typedef MotorDirection &MotorDirection_out;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct Motor;

  typedef
    ::TAO_Fixed_Var_T<
        Motor
      >
    Motor_var;

  typedef
    Motor &
    Motor_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  Motor
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef Motor_var _var_type;
    typedef Motor_out _out_type;
    
    Actuators::MotorDirection motor_direction;
    ::CORBA::Octet motor_speed;
    ::CORBA::Long motor_key;
    ::CORBA::Long motor_count;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:47

  enum SteeringOrientation
  {
    STEERING_LEFT,
    STEERING_RIGHT,
    STEERING_END
  };

  typedef SteeringOrientation &SteeringOrientation_out;

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct Steering;

  typedef
    ::TAO_Fixed_Var_T<
        Steering
      >
    Steering_var;

  typedef
    Steering &
    Steering_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct  Steering
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef Steering_var _var_type;
    typedef Steering_out _out_type;
    
    Actuators::SteeringOrientation steering_orientation;
    ::CORBA::Octet steering_angle;
    ::CORBA::Long steering_key;
    ::CORBA::Long steering_count;
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module Actuators

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:904

  template<>
  class Arg_Traits< ::Actuators::MotorDirection>
    : public
        Basic_Arg_Traits_T<
            ::Actuators::MotorDirection,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Actuators::Motor>
    : public
        Fixed_Size_Arg_Traits_T<
            ::Actuators::Motor,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:904

  template<>
  class Arg_Traits< ::Actuators::SteeringOrientation>
    : public
        Basic_Arg_Traits_T<
            ::Actuators::SteeringOrientation,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::Actuators::Steering>
    : public
        Fixed_Size_Arg_Traits_T<
            ::Actuators::Steering,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, Actuators::MotorDirection _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, Actuators::MotorDirection &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Actuators::Motor &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, Actuators::Motor &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, Actuators::SteeringOrientation _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, Actuators::SteeringOrientation &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Actuators::Steering &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, Actuators::Steering &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "MotorC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

