// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p15
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376


#include "MotorC.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "MotorC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_cs.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (TAO_OutputCDR &strm, Actuators::MotorDirection _tao_enumerator)
{
  return strm << static_cast< ::CORBA::ULong> (_tao_enumerator);
}

::CORBA::Boolean operator>> (TAO_InputCDR &strm, Actuators::MotorDirection & _tao_enumerator)
{
  ::CORBA::ULong _tao_temp = 0;
  ::CORBA::Boolean const _tao_success = strm >> _tao_temp;
  
  if (_tao_success)
    {
      _tao_enumerator = static_cast<Actuators::MotorDirection> (_tao_temp);
    }
  
  return _tao_success;
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Actuators::Motor &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.motor_direction) &&
    (strm << ::ACE_OutputCDR::from_octet (_tao_aggregate.motor_speed)) &&
    (strm << _tao_aggregate.motor_key) &&
    (strm << _tao_aggregate.motor_count);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Actuators::Motor &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.motor_direction) &&
    (strm >> ::ACE_InputCDR::to_octet (_tao_aggregate.motor_speed)) &&
    (strm >> _tao_aggregate.motor_key) &&
    (strm >> _tao_aggregate.motor_count);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_cs.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (TAO_OutputCDR &strm, Actuators::SteeringOrientation _tao_enumerator)
{
  return strm << static_cast< ::CORBA::ULong> (_tao_enumerator);
}

::CORBA::Boolean operator>> (TAO_InputCDR &strm, Actuators::SteeringOrientation & _tao_enumerator)
{
  ::CORBA::ULong _tao_temp = 0;
  ::CORBA::Boolean const _tao_success = strm >> _tao_temp;
  
  if (_tao_success)
    {
      _tao_enumerator = static_cast<Actuators::SteeringOrientation> (_tao_temp);
    }
  
  return _tao_success;
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Actuators::Steering &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.steering_orientation) &&
    (strm << ::ACE_OutputCDR::from_octet (_tao_aggregate.steering_angle)) &&
    (strm << _tao_aggregate.steering_key) &&
    (strm << _tao_aggregate.steering_count);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Actuators::Steering &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.steering_orientation) &&
    (strm >> ::ACE_InputCDR::to_octet (_tao_aggregate.steering_angle)) &&
    (strm >> _tao_aggregate.steering_key) &&
    (strm >> _tao_aggregate.steering_count);
}

TAO_END_VERSIONED_NAMESPACE_DECL



